[package]
name = "gaoc"
version = "0.1.0"
authors = ["Tri Nguyen <tri@trinnguyen.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.3"
log = "0.4.14"